"use client";
import {useEffect,useState} from "react";
export default function ResearchPage(){
 const [civil,setCivil]=useState(""),[enabled,setEnabled]=useState(false),[topics,setTopics]=useState<any[]>([]),[topic,setTopic]=useState(""),[file,setFile]=useState<File|null>(null),[stage,setStage]=useState<"login"|"upload"|"review"|"done">("login"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[msg,setMsg]=useState(""),[submission,setSubmission]=useState<any>(null),[trainee,setTrainee]=useState<any>(null);
 const load=async()=>{const r=await fetch("/api/research?action=topics");const d=await r.json();setEnabled(d.enabled);setTopics(d.topics||[]);};
 useEffect(()=>{load()},[]);
 const verify=async()=>{setError("");setBusy(true);try{const r=await fetch("/api/exam",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"verify",civil_id:civil})});const d=await r.json();if(!r.ok)throw new Error(d.error);setTrainee(d.trainee);setStage("upload");}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const upload=async()=>{setError("");setMsg("");if(!topic||!file){setError("اختر عنوان البحث وأرفق ملف PDF.");return}setBusy(true);try{const fd=new FormData();fd.append("civil_id",civil);fd.append("topic_id",topic);fd.append("file",file);const r=await fetch("/api/research",{method:"POST",body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);setSubmission(d.submission);setStage("review");}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 const confirm=async()=>{setBusy(true);setError("");try{const r=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"confirm",civil_id:civil,submission_id:submission.id})});const d=await r.json();if(!r.ok)throw new Error(d.error);setSubmission(d.submission);setStage("done");}catch(e:any){setError(e.message)}finally{setBusy(false)}};
 return <main dir="rtl" style={{minHeight:"100vh",background:"linear-gradient(135deg,#f3faf7,#eef5fb)",padding:"32px 16px",fontFamily:"Arial"}}><section style={{maxWidth:900,margin:"auto",background:"#fff",borderRadius:28,boxShadow:"0 18px 60px rgba(0,0,0,.08)",overflow:"hidden"}}><header style={{background:"linear-gradient(90deg,#006b5b,#0b8b72)",color:"#fff",padding:"28px"}}><b style={{fontSize:14}}>منصة اختبار المتدربين</b><h1 style={{fontSize:30,margin:"8px 0"}}>خدمة إرفاق البحث العلمي</h1><p style={{opacity:.9}}>اختيار عنوان البحث، رفع PDF، تدقيق التشابه، ثم التقييم الأكاديمي.</p></header><div style={{padding:28}}>{!enabled&&<div style={{padding:16,background:"#fff4e5",borderRadius:14,color:"#8a5a00",fontWeight:700}}>خدمة الأبحاث غير مفعلة حاليًا من مدير النظام.</div>}{error&&<div style={{padding:14,background:"#feecec",color:"#b42318",borderRadius:12,marginBottom:16}}>{error}</div>}{msg&&<div style={{padding:14,background:"#eaf8f1",color:"#087f69",borderRadius:12,marginBottom:16}}>{msg}</div>}
 {enabled&&stage==="login"&&<div><h2>التحقق من المتدرب</h2><p>أدخل السجل المدني للمتابعة.</p><input value={civil} maxLength={10} onChange={e=>setCivil(e.target.value.replace(/\D/g,""))} placeholder="10 أرقام" style={input}/><button disabled={busy||civil.length!==10} onClick={verify} style={button}>{busy?"جاري التحقق...":"متابعة"}</button></div>}
 {stage==="upload"&&<div><div style={card}><b>مرحبًا {trainee?.full_name}</b></div><h2>اختيار موضوع البحث</h2><select value={topic} onChange={e=>setTopic(e.target.value)} style={input}><option value="">اختر عنوان البحث</option>{topics.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select><h3>إرفاق البحث</h3><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} style={{...input,padding:10}}/><p style={{color:"#687b78",fontSize:13}}>PDF فقط. الحد الأعلى حسب إعدادات مدير النظام.</p><button disabled={busy} onClick={upload} style={button}>{busy?"جاري تدقيق البحث...":"إرسال البحث للتدقيق"}</button></div>}
 {stage==="review"&&<div><h2>تدقيق البحث</h2><div style={scoreBox}><b>نسبة التشابه النصي التقديرية</b><strong>{submission?.plagiarism_percent??0}%</strong><p>{submission?.plagiarism_summary}</p></div><div style={card}><p>قبل الإرسال النهائي، راجع النسبة واسم الملف. بعد التأكيد سيبدأ التقييم الأكاديمي.</p><b>{file?.name}</b></div><button disabled={busy} onClick={confirm} style={button}>{busy?"جاري التقييم الأكاديمي...":"تأكيد الإرسال النهائي"}</button></div>}
 {stage==="done"&&<div style={{textAlign:"center"}}><div style={{fontSize:56}}>✓</div><h2>تم إرسال البحث بنجاح</h2><p>تم حفظ البحث وإجراء التقييم الأكاديمي.</p><div style={scoreBox}><b>الدرجة الأكاديمية</b><strong>{submission?.academic_score??"—"} / 20</strong><p>{submission?.academic_feedback}</p></div></div>}
 </div></section></main>;
}
const input={width:"100%",padding:"14px",border:"1px solid #d7e5e1",borderRadius:12,margin:"8px 0 16px",fontSize:16,boxSizing:"border-box" as const};const button={background:"#087f69",color:"#fff",border:0,borderRadius:12,padding:"14px 22px",fontWeight:800,cursor:"pointer",width:"100%"};const card={background:"#f7faf9",padding:16,borderRadius:14,margin:"12px 0 20px"};const scoreBox={background:"#eef8f5",padding:20,borderRadius:18,margin:"18px 0",textAlign:"center" as const};