"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function AdminResearch(){
 const [topics,setTopics]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]),[enabled,setEnabled]=useState(false),[max,setMax]=useState(10),[title,setTitle]=useState(""),[desc,setDesc]=useState(""),[edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const headers=async():Promise<Record<string,string>>=>{const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:"Bearer "+session.access_token}:{}};
 const load=async()=>{setLoading(true);setError("");try{const h=await headers();if(!h.Authorization)throw new Error("انتهت جلسة مدير النظام. أعد تسجيل الدخول.");const r=await fetch("/api/research?action=submissions&ts="+Date.now(),{headers:h,cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"تعذر تحميل الأبحاث المقدمة.");setSubs(d.submissions||[]);const t=await fetch("/api/research?action=topics&ts="+Date.now(),{cache:"no-store"});const td=await t.json();setTopics(td.topics||[]);setEnabled(td.enabled===true);setMax(td.max_file_size_mb||10);setError("")}catch(e:any){setError(e?.message||"تعذر تحميل بيانات الأبحاث.");}finally{setLoading(false);}};
 useEffect(()=>{load()},[]);
 const saveTopic=async()=>{setError("");setMessage("");if(!title.trim()){setError("اكتب اسم عنوان البحث أولًا.");return}setBusy(true);try{const h=await headers();if(!h.Authorization){setError("انتهت جلسة مدير النظام. أعد تسجيل الدخول ثم حاول مرة أخرى.");return}const r=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"topic_save",id:edit?.id,title:title.trim(),description:desc,is_active:true})});const raw=await r.text();let d:any={};try{d=raw?JSON.parse(raw):{}}catch{d={error:raw}}if(!r.ok){setError(d.error||`تعذر حفظ عنوان البحث (HTTP ${r.status}).`);return}setTitle("");setDesc("");setEdit(null);setMessage("تم حفظ عنوان البحث بنجاح.");await load()}catch(e:any){setError(e?.message||"تعذر الاتصال بالخادم.")}finally{setBusy(false)}};
 const del=async(id:string)=>{if(!confirm("حذف عنوان البحث؟"))return;const h=await headers();await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"topic_delete",id})});await load()};
 const setting=async()=>{const h=await headers();await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"settings",enabled,max_file_size_mb:max})});setMessage("تم تحديث إعدادات الخدمة.");await load()};
 const grade=async(s:any)=>{const v=prompt("الدرجة من 20",String(s.academic_score??""));if(v===null)return;const f=prompt("ملاحظات التقييم",s.academic_feedback||"");const h=await headers();await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"grade",id:s.id,score:Number(v),feedback:f||""})});await load()};
 const download=async(id:string)=>{const h=await headers();const r=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"download",id})});const d=await r.json();if(d.url)window.open(d.url,"_blank")};
 return <main dir="rtl" style={{minHeight:"100vh",background:"#f4f8f7",padding:28,fontFamily:"Arial"}}><div style={{maxWidth:1250,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><div><div style={{color:"#087f69",fontWeight:800}}>إدارة النظام</div><h1 style={{margin:"6px 0"}}>إدارة الأبحاث العلمية</h1><p style={{color:"#687b78"}}>تفعيل الخدمة وإدارة عناوين الأبحاث ومراجعة الدرجات.</p></div><a href="/admin" style={{textDecoration:"none",color:"#087f69",fontWeight:800}}>← العودة للإدارة</a></div>{error&&<div style={{padding:14,background:"#feecec",color:"#b42318",borderRadius:12,marginBottom:16}}>{error}</div>}{message&&<div style={{padding:14,background:"#eaf8f1",color:"#087f69",borderRadius:12,marginBottom:16}}>{message}</div>}
 <section style={panel}><h2>إعدادات الخدمة</h2><label style={row}><span>تفعيل خدمة الأبحاث للمتدربين</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><label>الحد الأعلى للملف (MB)<input style={input} type="number" min={1} max={25} value={max} onChange={e=>setMax(Number(e.target.value))}/></label><button style={button} onClick={setting}>حفظ الإعدادات</button></section>
 <section style={panel}><h2>عناوين الأبحاث</h2><div style={{display:"grid",gridTemplateColumns:"1fr 2fr auto",gap:10}}><input style={input} placeholder="اسم عنوان البحث" value={title} onChange={e=>setTitle(e.target.value)}/><input style={input} placeholder="وصف اختياري" value={desc} onChange={e=>setDesc(e.target.value)}/><button type="button" style={{...button,opacity:busy?.65:1}} disabled={busy} onClick={saveTopic}>{busy?"جاري الحفظ…":edit?"تحديث":"إضافة"}</button></div><div>{topics.map(t=><div key={t.id} style={item}><div style={{minWidth:0,flex:1}}><div style={topicTitle}>{t.title}</div><div style={topicDesc}>{t.description||"بدون وصف"}</div></div><div style={actions}><button style={secondaryButton} onClick={()=>{setEdit(t);setTitle(t.title);setDesc(t.description||"")}}>تعديل</button><button style={dangerButton} onClick={()=>del(t.id)}>حذف</button></div></div>)}</div></section>
 <section style={panel}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,marginBottom:14}}><div><h2 style={{margin:"0 0 5px"}}>الأبحاث المقدمة</h2><div style={{color:"#687b78",fontSize:14}}>إجمالي الأبحاث: <strong>{subs.length}</strong></div></div><button style={secondaryButton} onClick={load} disabled={loading}>{loading?"جاري التحديث…":"↻ تحديث البيانات"}</button></div>{subs.length===0&&!loading&&<div style={{padding:22,textAlign:"center",background:"#f7faf9",borderRadius:12,color:"#687b78"}}>لا توجد أبحاث مقدمة حاليًا.</div>}<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th>المتدرب</th><th>العنوان</th><th>النسخ/التشابه</th><th>الدرجة</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{subs.map(s=><tr key={s.id} style={{borderTop:"1px solid #edf2f1"}}><td>{s.trainees?.full_name}<br/><small>{s.trainees?.civil_id}</small></td><td>{s.research_topics?.title}<br/><small>{s.file_name}</small></td><td>{s.plagiarism_percent??"—"}%</td><td>{s.academic_score??"—"} / 20</td><td>{s.status}</td><td><button onClick={()=>download(s.id)}>فتح PDF</button> <button onClick={()=>grade(s)}>تعديل الدرجة</button></td></tr>)}</tbody></table></div></section></div></main>;
}
const panel={background:"#fff",padding:24,borderRadius:20,marginBottom:18,boxShadow:"0 6px 25px rgba(15,74,66,.06)"};const input={width:"100%",padding:12,border:"1px solid #d7e5e1",borderRadius:10,boxSizing:"border-box" as const};const button={background:"#087f69",color:"#fff",border:0,borderRadius:10,padding:"11px 18px",fontWeight:800,cursor:"pointer"};const row={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 0",borderBottom:"1px solid #edf2f1"};const item={display:"flex",justifyContent:"space-between",alignItems:"center",gap:18,padding:"16px 4px",borderBottom:"1px solid #edf2f1"};const topicTitle={fontSize:17,fontWeight:800,color:"#123c36",lineHeight:1.6,marginBottom:4};const topicDesc={fontSize:14,color:"#71817e",lineHeight:1.7};const actions={display:"flex",gap:8,flexShrink:0};const secondaryButton={background:"#eef6f3",color:"#087f69",border:"1px solid #cfe3dd",borderRadius:9,padding:"9px 14px",fontWeight:800,cursor:"pointer"};const dangerButton={background:"#fff1f0",color:"#b42318",border:"1px solid #f3c8c4",borderRadius:9,padding:"9px 14px",fontWeight:800,cursor:"pointer"};