"use client";
import {useEffect,useState} from "react";
import {createClient} from "@supabase/supabase-js";
const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
export default function AdminResearch(){
 const [topics,setTopics]=useState<any[]>([]),[subs,setSubs]=useState<any[]>([]),[enabled,setEnabled]=useState(false),[max,setMax]=useState(10),[title,setTitle]=useState(""),[desc,setDesc]=useState(""),[edit,setEdit]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const headers=async()=>{const {data:{session}}=await sb.auth.getSession();return session?.access_token?{Authorization:"Bearer "+session.access_token}:{}};
 const load=async()=>{const h=await headers();const r=await fetch("/api/research",{headers:h});const d=await r.json();if(!r.ok){setError(d.error);return}setSubs(d.submissions||[]);const t=await fetch("/api/research?action=topics");const td=await t.json();setTopics(td.topics||[]);setEnabled(td.enabled);setMax(td.max_file_size_mb||10)};
 useEffect(()=>{load()},[]);
 const saveTopic=async()=>{if(!title.trim())return;setBusy(true);const h=await headers();const r=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"topic_save",id:edit?.id,title,description:desc,is_active:true})});const d=await r.json();if(!r.ok)setError(d.error);else{setTitle("");setDesc("");setEdit(null);setMessage("تم حفظ عنوان البحث.");await load()}setBusy(false)};
 const del=async(id:string)=>{if(!confirm("حذف عنوان البحث؟"))return;const h=await headers();await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"topic_delete",id})});await load()};
 const setting=async()=>{const h=await headers();await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"settings",enabled,max_file_size_mb:max})});setMessage("تم تحديث إعدادات الخدمة.");await load()};
 const grade=async(s:any)=>{const v=prompt("الدرجة من 20",String(s.academic_score??""));if(v===null)return;const f=prompt("ملاحظات التقييم",s.academic_feedback||"");const h=await headers();await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"grade",id:s.id,score:Number(v),feedback:f||""})});await load()};
 const download=async(id:string)=>{const h=await headers();const r=await fetch("/api/research",{method:"POST",headers:{"Content-Type":"application/json",...h},body:JSON.stringify({action:"download",id})});const d=await r.json();if(d.url)window.open(d.url,"_blank")};
 return <main dir="rtl" style={{minHeight:"100vh",background:"#f4f8f7",padding:28,fontFamily:"Arial"}}><div style={{maxWidth:1250,margin:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><div><div style={{color:"#087f69",fontWeight:800}}>إدارة النظام</div><h1 style={{margin:"6px 0"}}>إدارة الأبحاث العلمية</h1><p style={{color:"#687b78"}}>تفعيل الخدمة وإدارة عناوين الأبحاث ومراجعة الدرجات.</p></div><a href="/admin" style={{textDecoration:"none",color:"#087f69",fontWeight:800}}>← العودة للإدارة</a></div>{error&&<div style={{padding:14,background:"#feecec",color:"#b42318",borderRadius:12,marginBottom:16}}>{error}</div>}{message&&<div style={{padding:14,background:"#eaf8f1",color:"#087f69",borderRadius:12,marginBottom:16}}>{message}</div>}
 <section style={panel}><h2>إعدادات الخدمة</h2><label style={row}><span>تفعيل خدمة الأبحاث للمتدربين</span><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/></label><label>الحد الأعلى للملف (MB)<input style={input} type="number" min={1} max={25} value={max} onChange={e=>setMax(Number(e.target.value))}/></label><button style={button} onClick={setting}>حفظ الإعدادات</button></section>
 <section style={panel}><h2>عناوين الأبحاث</h2><div style={{display:"grid",gridTemplateColumns:"1fr 2fr auto",gap:10}}><input style={input} placeholder="اسم عنوان البحث" value={title} onChange={e=>setTitle(e.target.value)}/><input style={input} placeholder="وصف اختياري" value={desc} onChange={e=>setDesc(e.target.value)}/><button style={button} disabled={busy} onClick={saveTopic}>{edit?"تحديث":"إضافة"}</button></div><div>{topics.map(t=><div key={t.id} style={item}><div><b>{t.title}</b><small>{t.description||"بدون وصف"}</small></div><div><button onClick={()=>{setEdit(t);setTitle(t.title);setDesc(t.description||"")}}>تعديل</button><button onClick={()=>del(t.id)}>حذف</button></div></div>)}</div></section>
 <section style={panel}><h2>الأبحاث المقدمة</h2><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr><th>المتدرب</th><th>العنوان</th><th>النسخ/التشابه</th><th>الدرجة</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{subs.map(s=><tr key={s.id}><td>{s.trainees?.full_name}<br/><small>{s.trainees?.civil_id}</small></td><td>{s.research_topics?.title}<br/><small>{s.file_name}</small></td><td>{s.plagiarism_percent??"—"}%</td><td>{s.academic_score??"—"} / 20</td><td>{s.status}</td><td><button onClick={()=>download(s.id)}>فتح PDF</button> <button onClick={()=>grade(s)}>تعديل الدرجة</button></td></tr>)}</tbody></table></div></section></div></main>;
}
const panel={background:"#fff",padding:24,borderRadius:20,marginBottom:18,boxShadow:"0 6px 25px rgba(15,74,66,.06)"};const input={width:"100%",padding:12,border:"1px solid #d7e5e1",borderRadius:10,boxSizing:"border-box" as const};const button={background:"#087f69",color:"#fff",border:0,borderRadius:10,padding:"11px 18px",fontWeight:800,cursor:"pointer"};const row={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 0",borderBottom:"1px solid #edf2f1"};const item={display:"flex",justifyContent:"space-between",alignItems:"center",padding:"14px 0",borderBottom:"1px solid #edf2f1"};